#request all games
http://localhost:5086/games


###request game by id
http://localhost:5086/games/8


###create new game
POST http://localhost:5086/games
Content-Type: application/json

{
    "name": "Game 9",
    "genreId": 4,
    "price": 49.99,
    "releaseDate": "2023-03-01"
}


### Edit the game
PUT  http://localhost:5086/games/10
Content-Type: application/json

{
    "name": "Game 88",
    "genreId": 4,
    "price": 68.99,
    "releaseDate": "2025-03-01"
}



### Delete the game
DELETE http://localhost:5086/games/9